# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #

ARG VARIANT=latest

# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #

FROM oven/bun:${VARIANT}

# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #

# Install necessary packages: git, zsh etc
RUN apt-get update \
    && apt-get -y install --no-install-recommends \
    bash \
    curl \
    git \
    wget \
    zsh \
    && apt-get auto-remove -y \
    && apt-get clean -y \
    && chsh -s $(which bash) bun \
    && echo 'export PS1="\e[01;32m\u\e[m:\e[01;34m\w\e[m\$ "' >> /home/bun/.bashrc

# Install Oh My Zsh (if needed)
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install oh-my-zsh:
# Uses "Spaceship" theme with some customization. Uses some bundled plugins and installs some more from github
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t https://github.com/denysdovhan/spaceship-prompt \
    -a 'SPACESHIP_PROMPT_ADD_NEWLINE="false"' \
    -a 'SPACESHIP_PROMPT_SEPARATE_LINE="false"' \
    -p git \
    -p ssh-agent \
    -p https://github.com/zsh-users/zsh-autosuggestions \
    -p https://github.com/zsh-users/zsh-completions

# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #

USER bun

# //////////////////////////////////////////////////////////////////////////////////////////////////////////////////// #